### ISSUE TITLE
Frage: Einige Routen sind im PDF nicht korrekt

### ISSUE THREAD

**Issue by JonasGroeger** [poschi3/gelbersack#3]
Hallo Poschi,

ich hab das gleich auch schon mal für mich selbst gemacht. Ich kann mich noch daran erinnern dass in der PDF an manchen Stellen die Straße im PDF "übermalt" wurde. Wenn man den Text auswählt sieht man aber noch die alte Straße / Nummer etc.

Hast du das beachtet?

**Comment by poschi3** [comment]
Hallo Jonas,

mit Straßen mache ich nichts. Die Daten habe ich von der [Stadt](https://www.nuernberg.de/imperia/md/asn/dokumente/abfuhrplan_dsd_nuernberg_2017-2019_final.pdf). Einige der Termine habe ich auf Plausibilität geprüft.

Grüße
Flo
